; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=GAMAN Nomina
AppVersion=1.0.0
DefaultDirName={pf}\GAMAN Nomina
DefaultGroupName=GAMAN Nomina
OutputDir=C:\Automatizaciones\Nomina\instalador
OutputBaseFilename=Instalador_GAMAN_Nomina
Compression=lzma
SolidCompression=yes

[Files]
Source: "C:\Automatizaciones\Nomina\scripts\dist\GAMAN_Nomina.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Automatizaciones\Nomina\plantilla\NOMINA.xlsx"; DestDir: "{app}\plantilla"; Flags: ignoreversion

[Icons]
Name: "{group}\GAMAN Nomina"; Filename: "{app}\GAMAN_Nomina.exe"
Name: "{commondesktop}\GAMAN Nomina"; Filename: "{app}\GAMAN_Nomina.exe"

[Run]
Filename: "{app}\GAMAN_Nomina.exe"; Description: "Ejecutar GAMAN Nomina"; Flags: nowait postinstall skipifsilent
